##############################################################################
###                                                                        ###
###                            HERE BE SPOILERS                            ###
###                                                                        ###
##############################################################################
[spoilers]
spoilers = true

[brain]
suffers_from_confusion = true
max_num_memories = 15

[puzzle]
num_cols = 6
num_rows = 2
includes_question = true
introduction = "A man has barged into my room. He is asking all kinds of rude questions."
conclusion = "Oh that's right, this is my physician Dr. Walters. I don't know who told him to come over. There's nothing wrong with me."

[question]
phrase = "Who is this man?"

[answer]
phrase = "Physician"

[pairs.president]
face = "/080017_recolored.png"
phrase = "Prime Minister"

[pairs.library]
face = "/080019_recolored.png"
phrase = "Librarian"

[pairs.nurse]
face = "/080041_recolored.png"
phrase = "Janitor"

[pairs.scientist]
face = "/080175_recolored.png"
phrase = "Scientist"

[pairs.computer]
face = "/080216_recolored.png"
phrase = "Computer Guy"
