##############################################################################
###                                                                        ###
###                            HERE BE SPOILERS                            ###
###                                                                        ###
##############################################################################
[spoilers]
spoilers = true

[brain]
max_num_memories = 7

[puzzle]
num_cols = 6
num_rows = 2
includes_question = true
introduction = "I'm writing a letter to my sister, Mary. She never responds, but I want her to know I haven't forgotten about her."
conclusion = "Great, now I can send my letter."

[question]
phrase = "Who is this man?"

[answer]
phrase = "On a shelf"
